# Generated by Django 6.0.3 on 2026-04-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='materialsubmission',
            new_name='webapp_mate_user_id_f1e291_idx',
            old_name='webapp_mate_user_id_7403cd_idx',
        ),
        migrations.RenameIndex(
            model_name='materialsubmission',
            new_name='webapp_mate_created_fe84ee_idx',
            old_name='webapp_mate_created_dafc3b_idx',
        ),
    ]
