# Generated by Django 6.0.3 on 2026-04-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_community_interactions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitypostcomment',
            new_name='webapp_comm_post_id_33b9f7_idx',
            old_name='webapp_comm_post_id_8ddf98_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypostcomment',
            new_name='webapp_comm_post_id_5afe0f_idx',
            old_name='webapp_comm_post_id_7d96f7_idx',
        ),
    ]
