# Generated by Django 6.0.3 on 2026-04-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_rename_webapp_comm_post_id_8ddf98_idx_webapp_comm_post_id_33b9f7_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notification_type", models.CharField(choices=[("post_like", "Post like"), ("post_comment", "Post comment"), ("comment_reply", "Comment reply")], max_length=40)),
                ("message", models.CharField(max_length=255)),
                ("target_url", models.CharField(default="/user-dashboard/community/", max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="community_notification_events", to=settings.AUTH_USER_MODEL)),
                ("comment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="webapp.communitypostcomment")),
                ("post", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="webapp.communitypost")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="community_notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "-created_at"], name="webapp_comm_recipie_6caf8d_idx"),
                    models.Index(fields=["recipient", "is_read", "-created_at"], name="webapp_comm_recipie_212f5f_idx"),
                ],
            },
        ),
    ]
