# Generated by Django 6.0.3 on 2026-04-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_communitynotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitynotification',
            new_name='webapp_comm_recipie_ae9240_idx',
            old_name='webapp_comm_recipie_6caf8d_idx',
        ),
        migrations.RenameIndex(
            model_name='communitynotification',
            new_name='webapp_comm_recipie_c61ea5_idx',
            old_name='webapp_comm_recipie_212f5f_idx',
        ),
    ]
