# Generated by Django 6.0.3 on 2026-05-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_userprofile_account_role_roleapplication'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roleapplication',
            new_name='webapp_role_user_id_51170b_idx',
            old_name='wa_role_usr_rl_st_idx',
        ),
        migrations.RenameIndex(
            model_name='roleapplication',
            new_name='webapp_role_created_3ea519_idx',
            old_name='wa_role_crt_idx',
        ),
    ]
