# Generated by Django 6.0.3 on 2026-05-03 13:56

import django.db.models.deletion
import webapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_rename_wa_role_usr_rl_st_idx_webapp_role_user_id_51170b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country_code', models.CharField(default='+63', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery')], max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to=webapp.models.product_inquiry_screenshot_upload_to)),
                ('order_items', models.JSONField(default=list)),
                ('order_total', models.PositiveIntegerField(default=0)),
                ('admin_notification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['payment_method', '-created_at'], name='webapp_prod_payment_d9dedd_idx'), models.Index(fields=['-created_at'], name='webapp_prod_created_9c5973_idx')],
            },
        ),
    ]
