# Generated by Django 6.0.3 on 2026-05-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_roleapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotification',
            name='notification_type',
            field=models.CharField(choices=[('post_like', 'Post like'), ('post_comment', 'Post comment'), ('comment_reply', 'Comment reply'), ('role_application', 'Role application')], max_length=40),
        ),
    ]
