# Generated by Django 6.0.3 on 2026-05-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_merge_0014_alter_communitynotification_notification_type_0014_beneficiaryassistancerecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='beneficiaryassistancerecord',
            new_name='webapp_bene_benefic_acd33a_idx',
            old_name='webapp_bene_benefic_0d7f2f_idx',
        ),
        migrations.RenameIndex(
            model_name='beneficiaryassistancerecord',
            new_name='webapp_bene_assigne_97c58f_idx',
            old_name='webapp_bene_assigned_0a3ae1_idx',
        ),
    ]
