# Generated by Django 6.0.3 on 2026-05-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_activity'),
        ('webapp', '0018_donation'),
    ]

    operations = [
    ]
