# Generated by Django 6.0.3 on 2026-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_donation_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('store_product', 'Store Product'), ('relief_goods', 'Relief Goods'), ('hygiene_kit', 'Hygiene Kit'), ('school_supplies', 'School Supplies'), ('other', 'Other')], max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=150, null=True)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='webapp_dona_status_0c7f33_idx',
            old_name='don_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='webapp_dona_payment_143491_idx',
            old_name='don_method_created_idx',
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='webapp_dona_created_597a74_idx',
            old_name='don_created_idx',
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category', '-created_at'], name='webapp_inve_categor_39f0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['-created_at'], name='webapp_inve_created_429e9b_idx'),
        ),
    ]
