# Generated by Django 6.0.3 on 2026-05-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_inventoryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('restock', 'Restock'), ('deduct', 'Deduct')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='webapp.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', '-created_at'], name='webapp_stoc_item_id_ba1cf1_idx'), models.Index(fields=['-created_at'], name='webapp_stoc_created_c7d84d_idx')],
            },
        ),
    ]
