# Generated by Django 6.0.3 on 2026-05-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
