# Generated by Copilot on 2026-08-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0022_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="activity",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="community_post", to="webapp.activity"),
        ),
    ]
