# Generated by Django 6.0.3 on 2026-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_productinquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='delivery_country',
            field=models.CharField(default='Philippines', max_length=100),
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='delivery_province',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='delivery_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
