# Generated by Django 6.0.3 on 2026-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_productinquiry_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
