# Generated by Django 6.0.3 on 2026-05-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_volunteer_activity_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeractivityassignment',
            name='activity_type',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
