# Generated by Django 6.1 on 2026-08-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_communitypost_activity'),
        ('webapp', '0028_merge_0018_0027'),
    ]

    operations = [
    ]
