# Generated by Django 4.2.30 on 2026-08-31 07:09

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_activity_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='volunteerattendancerecord',
            new_name='webapp_volu_volunte_b8ccc1_idx',
            old_name='webapp_volu_volunte_attend_1_idx',
        ),
        migrations.RenameIndex(
            model_name='volunteerattendancerecord',
            new_name='webapp_volu_assignm_0659e9_idx',
            old_name='webapp_volu_assignme_attend_1_idx',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='official_receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=webapp.models.donation_official_receipt_upload_to),
        ),
        migrations.AddField(
            model_name='donation',
            name='official_receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='official_receipt_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productinquiry',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('card', 'Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skilllearningmaterialengagement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skilllearningtopicengagement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
