# Generated by Django 5.0 on 2026-09-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0037_alter_activity_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteeradminmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteeradminmessage",
            name="reply_to",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replies", to="webapp.volunteeradminmessage"),
        ),
    ]