# Generated by Django 4.2.30 on 2026-09-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_activity_category_and_image'),
        ('webapp', '0039_volunteeradminmessageattachment'),
    ]

    operations = [
    ]
