# Generated by Django 4.2.30 on 2026-09-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_beneficiaryactivityfeedback'),
        ('webapp', '0044_userprofile_required_ojt_hours'),
    ]

    operations = [
    ]
