# Generated by Django 4.2.30 on 2026-09-24 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_alter_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeractivityassignment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_assignments', to='webapp.activity'),
        ),
    ]
