# Generated by Django 4.2.30 on 2026-09-24 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0048_preserve_assignment_history_on_activity_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBeneficiaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_assignments', to='webapp.activity')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activity_beneficiaries', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_beneficiary_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['beneficiary__first_name', 'beneficiary__last_name', 'beneficiary_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='activitybeneficiaryassignment',
            constraint=models.UniqueConstraint(fields=('activity', 'beneficiary'), name='unique_activity_beneficiary_assignment'),
        ),
    ]
