# Generated by Django 4.2.30 on 2026-09-24 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0049_activitybeneficiaryassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotification',
            name='notification_type',
            field=models.CharField(choices=[('post_like', 'Post like'), ('post_comment', 'Post comment'), ('comment_reply', 'Comment reply'), ('role_application', 'Role application'), ('beneficiary_application_decision', 'Beneficiary application decision'), ('volunteer_application_decision', 'Volunteer application decision'), ('volunteer_assignment', 'Volunteer assignment'), ('activity_announcement', 'Activity announcement'), ('donation_impact', 'Donation impact update')], max_length=40),
        ),
        migrations.CreateModel(
            name='BeneficiaryActivityAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_attendance', to='webapp.activity')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_activity_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='beneficiaryactivityattendance',
            constraint=models.UniqueConstraint(fields=('activity', 'beneficiary'), name='unique_beneficiary_activity_attendance'),
        ),
    ]
