# Generated by Django 6.1 on 2026-09-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_donation_receipt_and_verification'),
        ('webapp', '0050_alter_communitynotification_notification_type_and_more'),
    ]

    operations = [
    ]
