# Generated by Django 4.2.30 on 2026-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_merge_20260924_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotification',
            name='notification_type',
            field=models.CharField(choices=[('post_like', 'Post like'), ('post_comment', 'Post comment'), ('comment_reply', 'Comment reply'), ('role_application', 'Role application'), ('beneficiary_application_decision', 'Beneficiary application decision'), ('volunteer_application_decision', 'Volunteer application decision'), ('volunteer_assignment', 'Volunteer assignment'), ('activity_end_reminder', 'Activity end reminder'), ('activity_announcement', 'Activity announcement'), ('donation_impact', 'Donation impact update')], max_length=40),
        ),
    ]
