# Generated by Django 4.2.30 on 2026-10-02 06:54

from django.conf import settings
from django.db import migrations, models
import uuid
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0054_beneficiaryattendance_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLibraryMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('rag-making', 'Rag-making'), ('teaching-kids', 'Teaching Kids'), ('planting', 'Planting'), ('outreach', 'Outreach')], max_length=30)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=webapp.models.resource_library_upload_to)),
                ('external_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
