# Generated by Django 4.2.30 on 2026-10-02 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0055_resourcelibrarymaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelibrarymaterial',
            name='custom_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='resourcelibrarymaterial',
            name='category',
            field=models.CharField(choices=[('rag-making', 'Rag-making'), ('teaching-kids', 'Teaching Kids'), ('planting', 'Planting'), ('outreach', 'Outreach'), ('other', 'Other')], max_length=30),
        ),
    ]
