# Generated by Django 4.2.30 on 2026-10-02 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0057_volunteer_ojt_schedule_and_duty_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSystemSettings',
            fields=[
                ('key', models.CharField(default='global', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
